name: crm-prod

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: change_me_in_production
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - /home/aselsis/crm/volumes/mariadb:/var/lib/mysql
    networks:
      - crm-network

  redis-cache:
    image: redis:alpine
    restart: always
    volumes:
      - /home/aselsis/crm/volumes/redis-cache:/data
    networks:
      - crm-network

  redis-queue:
    image: redis:alpine
    restart: always
    volumes:
      - /home/aselsis/crm/volumes/redis-queue:/data
    networks:
      - crm-network

  frappe:
    image: frappe/bench:latest
    restart: always
    command: bash /workspace/crm/docker/init_prod.sh
    user: root
    environment:
      - SHELL=/bin/bash
      - DB_ROOT_USER=frappe_admin
      - DB_ROOT_PASSWORD=change_me_in_production
      - ADMIN_PASSWORD=HelloWorldNoSpecialChars
      - SITE_NAME=${SITE_NAME:-crm.localhost}
    working_dir: /home/frappe
    volumes:
      - ..:/workspace/crm
      - /home/aselsis/crm/volumes/bench:/home/frappe/frappe-bench
      - /home/aselsis/crm/volumes/sites:/home/frappe/frappe-bench/sites
      - /home/aselsis/crm/volumes/logs:/home/frappe/frappe-bench/logs
    ports:
      - "${FRAPPE_PORT:-8076}:8000"
      - "${SOCKETIO_PORT:-9076}:9000"
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
